### PR TITLE
Jekyll update

### PR DESCRIPTION
**Pull request by dpshelio**
It updates jekyll and with it the md engine and uses remote_theme to get indigo working

It all started trying to create a link between pages :sweat_smile:

### CODE REVIEW

**Comment by dpshelio** [comment]
@mmcleod89 - for some reason I can assign you to review, even though you should be part of the group now (you weren't :scream_cat: )

**Review by mmcleod89 — COMMENTED** [review]
This seems good to me and I have managed to get it to build on my machine, although I think that the build instructions in the readme should be updated to reflect the changes that are made here (update jekyll version, install kramdown & jekyll-remote-theme) as well as some missing pre-requisites (pdflatex, pandoc) or how to build using a container with the appropriate tools.

**Comment by krishnakumarg1984** [comment]
I needed a clean/fresh ruby environment to build this. I have cleaned up the Gemfile requirements and have updated the README accordingly. Also added Gemfile.lock to gitignore.

**Comment by dpshelio** [comment]
Had to revert the changes in the `Gemfile` so the jekyll version is pinned so it builds on the 22.04 ubuntu version running on GhA now..
When any of you is happy with the changes, approve and merge.

**Review by JamieJQuinn — APPROVED** [review]
Spicy

**Pull request merged**
